/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/operations/": {
    get: operations["getOperations"];
    post: operations["createOperation"];
  };
  "/operations/{id}": {
    get: operations["getOperation"];
  };
  "/operations/names": {
    get: operations["getOperationNames"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    CreateBasket: {
      name: string;
    };
    Operation: {
      /** Format: int64 */
      id?: number;
      name?: string;
    };
    OperationName: {
      /** Format: int64 */
      id?: number;
      name?: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  getOperations: {
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["Operation"][];
        };
      };
    };
  };
  createOperation: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateBasket"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["Operation"];
        };
      };
    };
  };
  getOperation: {
    parameters: {
      path: {
        id: number;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["Operation"];
        };
      };
    };
  };
  getOperationNames: {
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["OperationName"][];
        };
      };
    };
  };
}
