/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/users/login": {
    post: operations["login"];
  };
  "/operations": {
    get: operations["getOperations"];
    post: operations["createOperation"];
  };
  "/users/me": {
    get: operations["authenticatedUser"];
  };
  "/operations/{id}": {
    get: operations["getOperation"];
  };
  "/operations/names": {
    get: operations["getOperationNames"];
  };
  "/actuator": {
    get: operations["links"];
  };
  "/actuator/health": {
    get: operations["handle"];
  };
  "/actuator/health/**": {
    get: operations["handle_1"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    Login: {
      username: string;
      password: string;
    };
    User: {
      username: string;
    };
    CreateOperation: {
      name: string;
    };
    Operation: {
      /** Format: int64 */
      id: number;
      name: string;
    };
    OperationName: {
      /** Format: int64 */
      id: number;
      name: string;
    };
    Link: {
      href?: string;
      templated?: boolean;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  login: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["Login"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["User"];
        };
      };
    };
  };
  getOperations: {
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["Operation"][];
        };
      };
    };
  };
  createOperation: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateOperation"];
      };
    };
    responses: {
      /** @description Created */
      201: {
        content: {
          "application/json": components["schemas"]["Operation"];
        };
      };
    };
  };
  authenticatedUser: {
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["User"];
        };
      };
    };
  };
  getOperation: {
    parameters: {
      path: {
        id: number;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["Operation"];
        };
      };
    };
  };
  getOperationNames: {
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["OperationName"][];
        };
      };
    };
  };
  links: {
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/vnd.spring-boot.actuator.v3+json": {
            [key: string]: {
              [key: string]: components["schemas"]["Link"];
            };
          };
          "application/vnd.spring-boot.actuator.v2+json": {
            [key: string]: {
              [key: string]: components["schemas"]["Link"];
            };
          };
          "application/json": {
            [key: string]: {
              [key: string]: components["schemas"]["Link"];
            };
          };
        };
      };
    };
  };
  handle: {
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/vnd.spring-boot.actuator.v3+json": Record<string, never>;
          "application/vnd.spring-boot.actuator.v2+json": Record<string, never>;
          "application/json": Record<string, never>;
        };
      };
    };
  };
  handle_1: {
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/vnd.spring-boot.actuator.v3+json": Record<string, never>;
          "application/vnd.spring-boot.actuator.v2+json": Record<string, never>;
          "application/json": Record<string, never>;
        };
      };
    };
  };
}
