spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/elp
    username: root
    password: toor
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
  sql:
    init:
      mode: always # Execute schema-*.sql and data-*.sql files
springdoc:
  show-actuator: true
  swagger-ui:
    csrf:
      enabled: true
logging:
  level:
    org:
      springframework:
        security: DEBUG
