spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/elp
    username: root
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    open-in-view: false
  sql:
    init:
      mode: always # Execute schema-*.sql and data-*.sql files
  mvc:
    log-request-details: true
springdoc:
  swagger-ui:
    csrf:
      enabled: true
server:
  servlet:
    session:
      timeout: 30m
      cookie:
        http-only: true
        same-site: strict
logging:
  level:
    de:
      eisingerf: DEBUG
    org:
      springframework:
        web: DEBUG
