spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/elp
    username: root
    password: toor
  jpa:
    hibernate:
      format-sql: true
      ddl-auto: create
    open-in-view: false
  sql:
    init:
      mode: always # Execute schema-*.sql and data-*.sql files
  mvc:
    log-request-details: true
  data:
    rest:
      default-media-type: application/json
springdoc:
  swagger-ui:
    csrf:
      enabled: true
  default-produces-media-type: application/json
server:
  servlet:
    session:
      timeout: 30m
      cookie:
        http-only: true
        same-site: strict
logging:
  level:
    de:
      eisingerf: DEBUG
    org:
      springframework:
        web: DEBUG
      hibernate:
        SQL: DEBUG
        type: TRACE
        orm:
          jdbc:
            bind: TRACE