openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
servers:
- url: http://localhost
  description: Generated server url
paths:
  /operations/:
    get:
      tags:
      - operation-controller
      operationId: getOperations
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Operation'
    post:
      tags:
      - operation-controller
      operationId: createOperation
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateBasket'
        required: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Operation'
  /operations/{id}:
    get:
      tags:
      - operation-controller
      operationId: getOperation
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Operation'
  /operations/names:
    get:
      tags:
      - operation-controller
      operationId: getOperationNames
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/OperationName'
components:
  schemas:
    CreateBasket:
      required:
      - name
      type: object
      properties:
        name:
          type: string
    Operation:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
    OperationName:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
